/*
 * Java domain class for entity "Address" 
 * Created on 2022-01-17 ( Date ISO 2022-01-17 - Time 14:05:33 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package com.fishdan.objects;

import java.io.Serializable;


/**
 * Domain class for entity "Address"
 *
 * @author Telosys Tools Generator
 *
 */
public class Address extends FishObject implements Serializable {


    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY 
    //----------------------------------------------------------------------
    private Integer    id           ;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    private Integer    personid     ;
    private String     street1      ;
    private String     street2      ;
    private String     city         ;
    private String     state        ;
    private String     county       ;
    private String     zip          ;
    private String     country      ;
    private String     type         ;

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Address() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR "KEY FIELD(S)"
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR "DATA FIELDS"
    //----------------------------------------------------------------------
    public void setPersonid( Integer personid ) {
        this.personid = personid ;
    }
    public Integer getPersonid() {
        return this.personid;
    }

    public void setStreet1( String street1 ) {
        this.street1 = street1 ;
    }
    public String getStreet1() {
        return this.street1;
    }

    public void setStreet2( String street2 ) {
        this.street2 = street2 ;
    }
    public String getStreet2() {
        return this.street2;
    }

    public void setCity( String city ) {
        this.city = city ;
    }
    public String getCity() {
        return this.city;
    }

    public void setState( String state ) {
        this.state = state ;
    }
    public String getState() {
        return this.state;
    }

    public void setCounty( String county ) {
        this.county = county ;
    }
    public String getCounty() {
        return this.county;
    }

    public void setZip( String zip ) {
        this.zip = zip ;
    }
    public String getZip() {
        return this.zip;
    }

    public void setCountry( String country ) {
        this.country = country ;
    }
    public String getCountry() {
        return this.country;
    }

    public void setType( String type ) {
        this.type = type ;
    }
    public String getType() {
        return this.type;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(personid);
        sb.append("|");
        sb.append(street1);
        sb.append("|");
        sb.append(street2);
        sb.append("|");
        sb.append(city);
        sb.append("|");
        sb.append(state);
        sb.append("|");
        sb.append(county);
        sb.append("|");
        sb.append(zip);
        sb.append("|");
        sb.append(country);
        sb.append("|");
        sb.append(type);
        return sb.toString(); 
    } 

}
