/*
 * Java domain class for entity "Email" 
 * Created on 2022-01-17 ( Date ISO 2022-01-17 - Time 14:05:33 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package com.fishdan.objects;

import java.io.Serializable;


/**
 * Domain class for entity "Email"
 *
 * @author Telosys Tools Generator
 *
 */
public class Email extends FishObject implements Personal {


    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY 
    //----------------------------------------------------------------------
	private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    private String     email        ;
	private Integer    personid     ;
    private String     type         ;
    private String     status       ;

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Email() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR "KEY FIELD(S)"
    //----------------------------------------------------------------------
    public void setEmail( String email ) {
        this.email = email ;
    }
    public String getEmail() {
        return this.email;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR "DATA FIELDS"
    //----------------------------------------------------------------------
    public void setPersonid( Integer personid ) {
        this.personid = personid ;
    }
    public Integer getPersonid() {
        return this.personid;
    }

    public void setType( String type ) {
        this.type = type ;
    }
    public String getType() {
        return this.type;
    }

    public void setStatus( String status ) {
        this.status = status ;
    }
    public String getStatus() {
        return this.status;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(email);
        sb.append("|");
        sb.append(personid);
        sb.append("|");
        sb.append(type);
        sb.append("|");
        sb.append(status);
        return sb.toString(); 
    }

	@Override
	public Integer getId() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setId(Integer id) {
		// TODO Auto-generated method stub
		
	} 

}
