/*
 * Java domain class for entity "Externalid" 
 * Created on 2022-01-17 ( Date ISO 2022-01-17 - Time 14:05:33 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package com.fishdan.objects;

import java.io.Serializable;


/**
 * Domain class for entity "Externalid"
 *
 * @author Telosys Tools Generator
 *
 */
public class Externalid extends FishObject implements Serializable {


    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY 
    //----------------------------------------------------------------------
    private Integer    id           ;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    private Integer    personid          ;
    private Integer    xid          ;
    private String     type         ;

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Externalid() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR "KEY FIELD(S)"
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR "DATA FIELDS"
    //----------------------------------------------------------------------
    public void setXid( Integer xid ) {
        this.xid = xid ;
    }
    public Integer getXid() {
        return this.xid;
    }

    public void setType( String type ) {
        this.type = type ;
    }
    public String getType() {
        return this.type;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(xid);
        sb.append("|");
        sb.append(type);
        return sb.toString(); 
    } 

}
