/*
 * Java domain class for entity "LinkPersonIssue" 
 * Created on 2022-01-17 ( Date ISO 2022-01-17 - Time 14:05:33 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package com.fishdan.objects;

import java.io.Serializable;


/**
 * Domain class for entity "LinkPersonIssue"
 *
 * @author Telosys Tools Generator
 *
 */
public class LinkPersonIssue extends FishObject implements Serializable {


    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY 
    //----------------------------------------------------------------------
    private Integer    id           ;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    private Integer    personid     ;
    private Integer    issueid      ;
    private Integer    create       ;
    private String     value        ;
    private Integer    score        ;

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public LinkPersonIssue() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR "KEY FIELD(S)"
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR "DATA FIELDS"
    //----------------------------------------------------------------------
    public void setPersonid( Integer personid ) {
        this.personid = personid ;
    }
    public Integer getPersonid() {
        return this.personid;
    }

    public void setIssueid( Integer issueid ) {
        this.issueid = issueid ;
    }
    public Integer getIssueid() {
        return this.issueid;
    }

    public void setCreate( Integer create ) {
        this.create = create ;
    }
    public Integer getCreate() {
        return this.create;
    }

    public void setValue( String value ) {
        this.value = value ;
    }
    public String getValue() {
        return this.value;
    }

    public void setScore( Integer score ) {
        this.score = score ;
    }
    public Integer getScore() {
        return this.score;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(personid);
        sb.append("|");
        sb.append(issueid);
        sb.append("|");
        sb.append(create);
        sb.append("|");
        sb.append(value);
        sb.append("|");
        sb.append(score);
        return sb.toString(); 
    } 

}
