/*
 * Java domain class for entity "Person" 
 * Created on 2022-01-17 ( Date ISO 2022-01-17 - Time 14:05:34 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package com.fishdan.objects;

import java.io.Serializable;
import java.lang.reflect.Field;


/**
 * Domain class for entity "Person"
 *
 * @author Telosys Tools Generator
 *
 */
public class Person extends FishObject implements Serializable {

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY 
    //----------------------------------------------------------------------
    private Integer    id           ;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    private String     prefix       ;
    private String     first        ;
    private String     middle       ;
    private String     last         ;
    private String     suffix       ;
    private Integer    birthdate    ;
    private String     gender       ;

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Person() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR "KEY FIELD(S)"
    //----------------------------------------------------------------------


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR "DATA FIELDS"
    //----------------------------------------------------------------------
    public void setPrefix( String prefix ) {
        this.prefix = prefix ;
    }
    public String getPrefix() {
        return this.prefix;
    }

    public void setFirst( String first ) {
        this.first = first ;
    }
    public String getFirst() {
        return this.first;
    }

    public void setMiddle( String middle ) {
        this.middle = middle ;
    }
    public String getMiddle() {
        return this.middle;
    }

    public void setLast( String last ) {
        this.last = last ;
    }
    public String getLast() {
        return this.last;
    }

    public void setSuffix( String suffix ) {
        this.suffix = suffix ;
    }
    public String getSuffix() {
        return this.suffix;
    }

    public void setBirthdate( String birthdate ) {
        this.birthdate = birthdate ;
    }
    public void setBirthdate( Integer birthdate ) {
        this.birthdate = birthdate ;
    }
    public Integer getBirthdate() {
        return this.birthdate;
    }

    public void setGender( String gender ) {
        this.gender = gender ;
    }
    public String getGender() {
        return this.gender;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(prefix);
        sb.append("|");
        sb.append(first);
        sb.append("|");
        sb.append(middle);
        sb.append("|");
        sb.append(last);
        sb.append("|");
        sb.append(suffix);
        sb.append("|");
        sb.append(birthdate);
        sb.append("|");
        sb.append(gender);
        return sb.toString(); 
    }

	public Field[] getFields() {
		// TODO Auto-generated method stub
		return fields;
	} 

}
